version: '3.2'
services:
  mongo:
    image: mongo:4.4.1-bionic
  api:
    ports:
      - "4000:4000"
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    environment:
      - API_MONGO__URI="mongodb://mongo/labyrinth"

